### ISSUE TITLE
Task not updating

### ISSUE THREAD

**Issue by MartinWa** [Azure/azure-sdk-for-media-services#186]
I have problems getting the progress of a task. I have tried both
`var progress = job.GetOverallProgress();`
and
` var task = job.Tasks.Where(j => j.Name == jobIdentifier).FirstOrDefault();
var progress = task.Progress;`

It seems like the tasks are not updated, they stay at 0 percent even if the value in the portal changes. If I restart my code while a job is processing (creating a new `CloudMediaContext` the progress is set corectly for the first call but does not update after that. I have also tried calling the 
`job.UpdateAsync()` with no effect.

**Comment by xpouyat** [comment]
Hello Martin,
Yes, there is a lot of caching happening for the context object.
You should try to refresh the job before getting the task progress.
job.Refresh();
Should work from my tests.

**Comment by MartinWa** [comment]
That works, thanks
