### ISSUE TITLE
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by todthomson** [Azure/azure-sdk-for-media-services#191]
Hi Azure SDK for Media Services,

Since upgrading `Microsoft.IdentityModel.Clients.ActiveDirectory` to `3.17.0` I am getting the following error:

```
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.1.846, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

It looks like `3.17.0` of `Microsoft.IdentityModel.Clients.ActiveDirectory` removes `Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll` completely, see:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/862
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/854

Going back to `3.16.1` fixes the issue.

Just wanted to let you know in case you weren't aware of what's happening from `Microsoft.IdentityModel.Clients.ActiveDirectory` from `3.17.0` moving forward.

I presume what's required in this project is a new `windowsazure.mediaservices` release that removes the dependency on `Microsoft.IdentityModel.Clients.ActiveDirectory.Platform`, but I'm not 100% sure?

If I can assist in any way please let me know :)

Thanks,

Tod.

**Comment by kpanwar** [comment]
thats exactly what is needed.

**Comment by tomgruszowski** [comment]
Anything? This is a dependency for one of Azure SDKs, doesn't anyone else have this same issue?

**Comment by dkfrya** [comment]
I also encounter the same problem.

This problem did not occur when referring to Microsoft.IdentityModel.Clients.ActiveDirectory 3.16.1.

I updated windowsazure.mediaservices.4.1.0, but this problem was not solved.
still need a reference to Microsoft.IdentityModel.Clients.ActiveDirectory.Platform 3.13.1.

Anyway, I returned to Microsoft.IdentityModel.Clients.ActiveDirectory 3.16.1, but it is not clean.

**Comment by todthomson** [comment]
Upgrading to `Microsoft.IdentityModel.Clients.ActiveDirectory` version `3.19.2` looks to have fixed it for me 👍

**Comment by emiliavanderwerf** [comment]
This was my situation and what worked for me:

I was using the `Microsoft.IdentityModel.Clients.ActiveDirectory` version 3.19 in a class library project but only had version 2.22 installed in the actual ASP.NET Web Application project. Upgrading to 3.19 in the web app project got me past the error.

**Comment by todthomson** [comment]
Closing as this has been fixed (we have two instances of it being fixed and noone else complaining).

**Comment by mamoorkhan** [comment]
I have a couple of libraries which I am referencing from my web project, I don't have this `Microsoft.IdentityModel.Clients.ActiveDirectory` nuget package installed on my web project, but on my reference assembly project. When I build, only the `Microsoft.IdentityModel.Clients.ActiveDirectory.dll` file gets copied to the web project and not the `Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll` despite it being referenced in the outer assembly project. Hence it is giving the error 

`Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.0.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`

**Comment by rustamm** [comment]
I had a similar error when using package version 4.5.0, but it was complaining about wrong assembly manifest. Downgrading to 3.19.8 helped.

**Comment by konrad-jamrozik** [comment]
Same situation and fix as @rustamm

**Comment by Zenuka** [comment]
Same issue here, can't update to any version 4.x since the `Microsoft.IdentityModel.Clients.ActiveDirectory.Platform` is missing

**Comment by pavansarma93** [comment]
The issue again got introduced in 4.x versions and still present in latest 5.1 as well. Hope this will be take care @todthomson

**Comment by nickbnick** [comment]
Same issue.

**Comment by aRajeshKumar** [comment]
Receiving the following error: 

Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.)

**Comment by rajarshi-singh** [comment]
This seems to be fixed in version 5.2.0

**Comment by gogoaic** [comment]
Update projects to the same - latest Nuget version Microsoft.IdentityModel.Clients.ActiveDirectory (5.2.6 now). This solved my problem. 5.0.5 version doesn't exist any more in Nuget and throws this error from nowhere today on the server

**Comment by shsingla** [comment]
I am still hitting the same issue Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform. It comes in 5.2.6 as well. The dll itself is not present. What is the fix for this ?

**Comment by Maughanstrosity** [comment]
+1 Watching

**Comment by alohaninja** [comment]
Ran into this same issue updating ADAL v3 to ADAL v5 - not specific to AMS SDK though - the fix that worked for me is to remove any references in your `CSPROJ` and the leftover binding redirects in your `app.config`. There is a breaking change moving off v3 - you just need to cleanup the previous references that nuget package manager updates won't automatically touch. 

### Error Message
```
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): Error MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.19.1.3001, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
```

### ADAL v3 Nuget Package DLLs
![image](https://user-images.githubusercontent.com/26234626/80868387-13294c00-8c4f-11ea-890c-7676691cd910.png)

### ADAL v5 Nuget Package DLLs
![image](https://user-images.githubusercontent.com/26234626/80868450-7915d380-8c4f-11ea-8072-19d54f1f2951.png)

### CSPROJ References
![image](https://user-images.githubusercontent.com/26234626/80868306-8ed6c900-8c4e-11ea-8c70-534c758eebd0.png)

### App.config Assembly Binding Redirects
![image](https://user-images.githubusercontent.com/26234626/80868323-add55b00-8c4e-11ea-9871-7b39131b171e.png)

**Comment by rkpv78** [comment]
Watching +1
  Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11

**Comment by clarkezone** [comment]
I'm hitting this as well

**Comment by Wind010** [comment]
I hit this, but with using the `AddAzureKeyVault` extension method.  I removed the package and added it back, which fixed the issue.

**Comment by priyanka22sakshi** [comment]
Thanks @Wind010 for this. I got it solved by using your method. for 5.2.8 version 👍

**Comment by tonderflash** [comment]
i resolve this using Microsoft.Identity.Client
