### ISSUE TITLE
Not able to update Xamarin.Forms 5.0 in project because of Microsoft.IdentityModel.Clients.ActiveDirectory nugets has dependency in Mono.Android8.1

### ISSUE THREAD

**Issue by MridulMalviya** [Azure/azure-sdk-for-media-services#218]
Xamarin.Android.Support.CustomTabs (>= 27.0.2.1)
Xamarin.Android.Support.v7.AppCompat (>= 27.0.2.1)
![Uploading Screenshot 2021-06-10 at 1.18.53 PM.png…]()

**Comment by xpouyat** [comment]
Hello,
You should move to the new SDK https://www.nuget.org/packages/Microsoft.Azure.Management.Media/
For the authentication, you can move from ADAL to MSAL library https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview
The samples [here ](https://github.com/Azure-Samples/media-services-v3-dotnet) use now MSDAL for authentication for AMS.
Code is https://github.com/Azure-Samples/media-services-v3-dotnet/blob/main/Common_Utils/Authentication.cs
